CREATE TABLE change_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by VARCHAR2(100) DEFAULT USER NOT NULL,
    script_name VARCHAR2(255) NOT NULL,
    script_details CLOB
);

INSERT INTO change_log (created_by, script_name, script_details) 
VALUES (
    'Sakib',
    '000_change_log.sql',
    'Initial creation of change_log table.'
);

COMMIT;

SELECT 'Change log table created successfully!' AS status FROM dual;